# Generated by Django 5.0.3 on 2025-09-16 18:49

import django.db.models.deletion
import django_tenants.postgresql_backend.base
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=None, max_length=80, null=None)),
                ('plan_type', models.CharField(choices=[('FR', 'Free'), ('PL', 'Professional'), ('OG', 'Organisation')], default='FR', max_length=2)),
                ('created_date', models.DateField(auto_now=True)),
                ('subscribed', models.BooleanField(blank=None, default=False, null=None)),
                ('password', models.CharField(blank=None, max_length=60, null=None)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['id'], name='main_client_id_add76e_idx')],
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='main.client')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
